# Generated by Django 3.2.22 on 2023-10-25 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iphoneblog', '0002_alter_post_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='iPhone_type',
            field=models.TextField(default=True),
            preserve_default=False,
        ),
    ]
