# Generated by Django 3.2.22 on 2023-10-27 16:02

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iphoneblog', '0006_author'),
    ]

    operations = [
        migrations.CreateModel(
            name='Smartphone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=100)),
                ('smartphone_image', cloudinary.models.CloudinaryField(default='placeholder', max_length=255, verbose_name='image')),
                ('slug', models.SlugField(default='', max_length=100, null=True, unique=True)),
                ('excerpt', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Smartphone',
                'verbose_name_plural': 'Smartphones',
            },
        ),
        migrations.AddField(
            model_name='post',
            name='battery_life',
            field=models.CharField(default=True, max_length=200, verbose_name='Average battery life'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='post',
            name='best_feature',
            field=models.CharField(default=False, max_length=150, verbose_name='Best feature of the smartphone'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='post',
            name='comment_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='post',
            name='smartphones',
            field=models.ManyToManyField(blank=True, to='iphoneblog.Smartphone'),
        ),
    ]
